### PR TITLE
Update to m2crypto 0.36.0

### PR DESCRIPTION
**Pull request by sjorge**
Compiles against newer SSL now

### CODE REVIEW

**Comment by sjorge** [comment]
@jperkin not tested on netbsd, having some issues on my build servers and need salt to fix it, and well salt needs this -_-

**Comment by jperkin** [comment]
I needed to make a couple of changes, but this has now been committed, thanks!

**Comment by sjorge** [comment]
Thanks, what changes did you have to make? (linked commit, is for ruby-recog)

**Comment by jperkin** [comment]
It'll show up in the next push.

**Pull request closed without merging**
