### PR TITLE
Configures to actually select Lua 5.3 - again?

### PR DESCRIPTION
**Pull request by goekesmi**
This commit updates the haproxy build options to make sure it uses Lua 5.3.  Otherwise, the build options were selecting Lua 5.2, and that's not compatible with haproxy.

### CODE REVIEW

**Comment by jperkin** [comment]
I merged a variant of the upstream change to fix this, thanks!

**Comment by goekesmi** [comment]
I'm very sorry to report that your fix does not seem to have fixed the problem.

I'm building from the pkgsrc-19.4 image, updated from the github 2019Q4 branch, with your fix.

```
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> git status                                          
On branch joyent/release/2019Q4
Your branch is up to date with 'origin/joyent/release/2019Q4'.

```

```
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> cat options.mk 
# $NetBSD: options.mk,v 1.7 2019/08/03 20:37:19 morr Exp $

PKG_OPTIONS_VAR=        PKG_OPTIONS.haproxy
PKG_SUPPORTED_OPTIONS=  pcre ssl deviceatlas lua prometheus
PKG_SUGGESTED_OPTIONS=  pcre ssl

.include "../../mk/bsd.options.mk"

###
### Use libpcre rather than libc for header processing regexp
###
.if !empty(PKG_OPTIONS:Mpcre)
.  include "../../devel/pcre/buildlink3.mk"
BUILD_MAKE_FLAGS+=      USE_PCRE=1
.endif

###
### Use LUA
###
.if !empty(PKG_OPTIONS:Mlua)
LUA_VERSION_ACCEPTED=   53
.  include "../../lang/lua/luaversion.mk"
BUILD_MAKE_FLAGS+=      USE_LUA=1
BUILD_MAKE_FLAGS+=      LUA_LIB_NAME=lua5.3
.  include "../../lang/lua/buildlink3.mk"
.endif

###
### Use Prometheus
###
.if !empty(PKG_OPTIONS:Mprometheus)
BUILD_MAKE_FLAGS+=      EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"
.endif


###
### Support DeviceAtlas detection.
###
.if !empty(PKG_OPTIONS:Mpcre) && !empty(PKG_OPTIONS:Mdeviceatlas)
DEVICEATLAS_VERSION=    2.1
DEVICEATLAS_DISTFILE=   deviceatlas-enterprise-c-${DEVICEATLAS_VERSION}
DISTFILES=              ${DISTNAME}.tar.gz ${DEVICEATLAS_DISTFILE}.zip
DEVICEATLAS_HOMEPAGE=   https://www.deviceatlas.com/deviceatlas-haproxy-module

BUILD_MAKE_FLAGS+=      USE_DEVICEATLAS=1 DEVICEATLAS_SRC=../${DEVICEATLAS_DISTFILE}

.  if !exists(${DISTDIR}/${DEVICEATLAS_DISTFILE}.zip)
FETCH_MESSAGE=          "Please fetch ${DEVICEATLAS_DISTFILE}.zip manually from"
FETCH_MESSAGE+=         "${DEVICEATLAS_HOMEPAGE}"
FETCH_MESSAGE+=         "and put into"
FETCH_MESSAGE+=         "${DISTDIR}"
.  endif
.endif

###
### Support OpenSSL for termination.
###
.if !empty(PKG_OPTIONS:Mssl)
.  include "../../security/openssl/buildlink3.mk"
BUILD_MAKE_FLAGS+=      USE_OPENSSL=1
.endif
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--

```

```
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> bmake PKG_OPTIONS.haproxy="pcre ssl lua prometheus" 
=> Bootstrap dependency digest>=20010302: found digest-20190127
=> Checksum SHA1 OK for haproxy-2.0.13.tar.gz
=> Checksum RMD160 OK for haproxy-2.0.13.tar.gz
=> Checksum SHA512 OK for haproxy-2.0.13.tar.gz
===> Installing dependencies for haproxy-2.0.13
==========================================================================
The supported build options for haproxy are:

        deviceatlas lua pcre prometheus ssl

The currently selected options are:

        lua pcre prometheus ssl

You can select which build options to use by setting PKG_DEFAULT_OPTIONS
or the following variable.  Its current value is shown:

        PKG_OPTIONS.haproxy = pcre ssl lua prometheus

==========================================================================
==========================================================================
The following variables will affect the build process of this package,
haproxy-2.0.13.  Their current value is shown below:

        * CURSES_DEFAULT = ncurses
        * LUA_VERSION_DEFAULT = 52
        * READLINE_DEFAULT = readline
        * SSLBASE (defined)
        * SSLCERTS = /opt/local/etc/openssl/certs
        * SSLDIR = /opt/local/etc/openssl
        * SSLKEYS = /opt/local/etc/openssl/private

Based on these variables, the following variables have been set:

        * CURSES_TYPE = ncurses
        * LUA_PACKAGE = lua52
        * READLINE_TYPE = readline
        * TERMCAP_TYPE = curses

You may want to abort the process now with CTRL-C and change their value
before continuing.  Be sure to run `/opt/local/bin/bmake clean' after
the changes.
==========================================================================
=> Tool dependency gmake>=3.81: found gmake-4.2.1nb1
=> Tool dependency checkperms>=1.1: found checkperms-1.12
=> Build dependency gcc7>=7.3: NOT found
=> Verifying bin-install for ../../lang/gcc7
^C
```

You will note that it selected LUA_PACKAGE = lua52, and then the compile fails.

I don't claim to know what the right way is, but I know that the patch I submitted does get the build system to pick the right lua package.

```
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> git checkout haproxy-lua
M       joyent
Switched to branch 'haproxy-lua'
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> bmake clean
===> Cleaning for haproxy-2.0.13
--<root@b15377e8-5814-49df-bc05-b19c169c5e47>-(/data/chroot/dev-2019Q4-x86_64)-</data/pkgsrc/net/haproxy>--
-> bmake PKG_OPTIONS.haproxy="pcre ssl lua prometheus" 
=> Bootstrap dependency digest>=20010302: found digest-20190127
=> Checksum SHA1 OK for haproxy-2.0.13.tar.gz
=> Checksum RMD160 OK for haproxy-2.0.13.tar.gz
=> Checksum SHA512 OK for haproxy-2.0.13.tar.gz
===> Installing dependencies for haproxy-2.0.13
==========================================================================
The supported build options for haproxy are:

        deviceatlas lua pcre prometheus ssl

The currently selected options are:

        lua pcre prometheus ssl

You can select which build options to use by setting PKG_DEFAULT_OPTIONS
or the following variable.  Its current value is shown:

        PKG_OPTIONS.haproxy = pcre ssl lua prometheus

==========================================================================
==========================================================================
The following variables will affect the build process of this package,
haproxy-2.0.13.  Their current value is shown below:

        * CURSES_DEFAULT = ncurses
        * LUA_VERSION_DEFAULT = 52
        * READLINE_DEFAULT = readline
        * SSLBASE (defined)
        * SSLCERTS = /opt/local/etc/openssl/certs
        * SSLDIR = /opt/local/etc/openssl
        * SSLKEYS = /opt/local/etc/openssl/private

Based on these variables, the following variables have been set:

        * CURSES_TYPE = ncurses
        * LUA_PACKAGE = lua53
        * READLINE_TYPE = readline
        * TERMCAP_TYPE = curses

You may want to abort the process now with CTRL-C and change their value
before continuing.  Be sure to run `/opt/local/bin/bmake clean' after
the changes.
==========================================================================
=> Tool dependency gmake>=3.81: found gmake-4.2.1nb1
=> Tool dependency checkperms>=1.1: found checkperms-1.12
=> Build dependency gcc7>=7.3: NOT found
=> Verifying bin-install for ../../lang/gcc7
===> Binary install for gcc7>=7.3
=> Installing gcc7>=7.3 from /data/packages/SmartOS/2019Q4/x86_64/All;http://0.0.0.0:8080/packages/SmartOS/2019Q4/x86_64//All
^C
```
Thus I'm re-opening this merge request.

**Comment by jperkin** [comment]
Heh oops, looks like I can't spell `LUA_VERSIONS_ACCEPTED` correctly, will push a fix for this shortly.

**Comment by goekesmi** [comment]
I've tested and that works.  Thanks.

**Pull request closed without merging**
